### ISSUE TITLE
Douyin 有几个受影响的地方

### ISSUE THREAD

**Issue by ConnersHua** [Choler/Surge#17]
1. `^https?:\/\/api.*\.amemv\.com\/aweme\/v\d\/comment`
影响评论，表现为部分评论会出现评论者回复自己的评论，且评论内容和被回复内容一致

2.  `^https?:\/\/api.*\.amemv\.com\/aweme\/v\d\/namek`
地点商家的团购套餐的详情无法加载

3.  `^https?:\/\/api.*\.amemv\.com\/aweme\/v\d\/shop`
商品的购买选项无法加载

**Comment by 2kuai** [comment]
感谢反馈，已在新项目中修复。[Module](https://raw.githubusercontent.com/2kuai/Surge/main/Module/douyin.sgmodule)
