### ISSUE TITLE
请问一下youtube js QuantumultX 版本的有吗？ 

### ISSUE THREAD

**Issue by zhiyicai** [Choler/Surge#2]
您好
请问一下youtube js QuantumultX 版本的有吗？ 
等待您的恢复

**Comment by Choler** [comment]
Quan 用reject-img 应该是同样的效果

**Comment by zhiyicai** [comment]
> Quan 用reject-img 应该是同样的效果

您指的是这样吗？
[rewrite_local]
// Youtube ADs
^https?:\/\/.+\.googlevideo\.com\/.+&oad url reject-img
^https?:\/\/.+\.googlevideo\.com\/.+ctier url reject-img
^https?:\/\/.+\.googlevideo\.com\/ptracking\?pltype=adhost url reject-img
^https?:\/\/.+\.googlevideo\.com\/videogoodput\? url reject-img
^https?:\/\/.+\.youtube\.com\/.+get_ads url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads url reject-img
^https?:\/\/.+\.youtube\.com\/error_204 url reject-img
^https?:\/\/.+\.youtube\.com\/get_midroll url reject-img
^https?:\/\/.+\.youtube\.com\/pagead\/* url reject-img
^https?:\/\/.+\.youtube\.com\/ptracking\? url reject-img
^https?:\/\/play.googleapis.com/log* url reject-img
^https?:\/\/www.googleapis.com/adsmeasurement/* url reject-img
^https?:\/\/youtubei.googleapis.com/youtubei/.+ad_ url reject-img
^https?:\/\/youtubei.googleapis.com/youtubei/.+log_ url reject-img
^https?:\/\/api\d?\.tiktokv\.com\/api\/ad\/ url reject-img
^https?:\/\/api\d?\.musical\.ly\/api\/ad\/ url reject-img


hostname = *.googlevideo.com,*.youtube.com,play.googleapis.com,www.googleapis.com,youtubei.googleapis.com

我参试过Youtube App 还是有广告
期待您的回复！

**Comment by zhiyicai** [comment]
如果采用您的，YouTube.js 在Surge 是可以直接过滤 Youtube app 广告的但是Quantumult不行

[rewrite_local]
#youtube
^https:\/\/[\s\S]*\.googlevideo\.com/.*&(oad|ctier) url script-response-body YouTube.js

- YouTube.js 在本地Quantumult X, Scripts文件夹里面了
